;; (car ''abracadabra) is interpreted as (car (quote (quote abracadabra)))
;; by the interpreter, and therefore, car evaluate to the first symbol of the list
;; generated by the first quote (quote abracadabra). That is, the first occurrence
;; of quote quotes the next symbol, which happens to be a list with two symbols -
;; (quote abracadabra).


